// Shared by the scripts that make puzzles ahead of time (dailies and the library).
import { fork } from "node:child_process";
import { readFileSync, renameSync, writeFileSync } from "node:fs";
import {
  DIFFICULTIES,
  Grid,
  REQUIREMENTS,
  TECHNIQUES,
  TEMPLATES,
  decodePuzzle,
  encodePuzzle,
  generateRatedSync,
  logicalSolve,
  missingMoves,
  moveCounts,
  spreadOf,
} from "../src/engine";
import type { Group } from "../src/engine";

export const DAILY_FILE = "src/daily-data.ts";
export const LIBRARY_FILE = "src/library-data.ts";

/** Write a file in one go (a crash or stop halfway never leaves half a file). */
export function writeSafely(path: string, text: string): void {
  writeFileSync(`${path}.tmp`, text);
  renameSync(`${path}.tmp`, path);
}

/** Whether a puzzle fits its template and has every move and lock REQUIREMENTS asks for. */
export function meetsRequirements(code: string, g: Group): boolean {
  const tech = TECHNIQUES.filter((t) => TEMPLATES[g].includes(t.name));
  const log = logicalSolve(new Grid(decodePuzzle(code)), tech);
  if (!log.solved) return false;
  const req = REQUIREMENTS[g];
  return !req || (!missingMoves(moveCounts(log.steps), req) && spreadOf(log.steps).locks >= (req.locks ?? 0));
}

/** The daily puzzles as they are on disk now (read at run time, so always up to date). */
export function readDailies(): { start: string; rows: string[][] } {
  const text = readFileSync(DAILY_FILE, "utf8");
  const start = /DAILY_START = "([0-9-]+)"/.exec(text)?.[1];
  if (!start) throw new Error(`No DAILY_START in ${DAILY_FILE}`);
  const rows = [...text.matchAll(/^\s+"([^"]+)",/gm)].map((m) => m[1].split(" "));
  return { start, rows };
}

/** Date of day i of a daily list starting at `start` (YYYY-MM-DD). */
export function dayOf(start: string, i: number): string {
  const d = new Date(`${start}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + i);
  return d.toISOString().slice(0, 10);
}

export function writeDailies(start: string, rows: string[][]): void {
  writeSafely(
    DAILY_FILE,
    `// Daily puzzles, generated by scripts/make-dailies.ts and scripts/grow.ts. Do not edit by hand.
// One line per day from DAILY_START: puzzle codes for ${DIFFICULTIES.join(", ")}.
export const DAILY_START = "${start}";
export const DAILY: string[] = [
${rows.map((r, i) => `  "${r.join(" ")}", // ${dayOf(start, i)}`).join("\n")}
];
`,
  );
}

/** The library as it is on disk now. */
export function readLibrary(): { library: Record<string, string[]>; likes: Record<string, string[]> } {
  const text = readFileSync(LIBRARY_FILE, "utf8");
  const [libPart, likePart = ""] = text.split("export const LIKES");
  const library: Record<string, string[]> = Object.fromEntries(DIFFICULTIES.map((g) => [g, []]));
  let cur: string | null = null;
  for (const line of libPart.split(/\r?\n/)) {
    const head = /^\s+(\w+): \[/.exec(line);
    if (head) cur = head[1];
    const code = /^\s+"([^"]+)",/.exec(line);
    if (code && cur) (library[cur] ??= []).push(code[1]);
  }
  const likes: Record<string, string[]> = {};
  for (const m of likePart.matchAll(/^\s+(\w+): \[([^\]]*)\]/gm)) likes[m[1]] = [...m[2].matchAll(/"([^"]*)"/g)].map((x) => x[1]);
  return { library, likes };
}

/**
 * A puzzle of a template that has all the moves REQUIREMENTS asks for, searched without
 * a time limit (up to 3 rounds of 20 candidates; the best one if none gets there).
 */
export function goodPuzzle(g: Group, rnd: () => number): { code: string; missing: number } {
  const allowed = TEMPLATES[g];
  if (!REQUIREMENTS[g]) return { code: encodePuzzle(generateRatedSync({ allowed }, rnd).puzzle), missing: 0 };
  let best: { code: string; missing: number } | null = null;
  for (let round = 0; round < 3; round++) {
    const r = generateRatedSync({ allowed, maxCandidates: 20, triesPerCandidate: 3000 }, rnd);
    if (!best || r.missing < best.missing) best = { code: encodePuzzle(r.puzzle), missing: r.missing };
    if (!best.missing) break;
  }
  return best!;
}

/**
 * Run make(i) for i = 0..n-1 on several processes. In the parent it returns the results;
 * in a worker process (started by this function) it does its share and exits.
 */
export function parallel<T>(n: number, make: (i: number) => T, workers: number, label = "done"): Promise<T[]> {
  const part = process.env.POOL_PART;
  if (part) {
    const [k, w] = part.split("/").map(Number);
    for (let i = k; i < n; i += w) process.send!({ i, value: make(i) });
    process.exit(0);
  }
  const out = new Array<T>(n);
  const t0 = Date.now();
  let done = 0;
  return Promise.all(
    Array.from(
      { length: Math.min(workers, n) },
      (_, k) =>
        new Promise<void>((resolve, reject) => {
          const child = fork(process.argv[1], process.argv.slice(2), { env: { ...process.env, POOL_PART: `${k}/${Math.min(workers, n)}` } });
          child.on("message", (m: { i: number; value: T }) => {
            out[m.i] = m.value;
            if (++done % 20 === 0 || done === n) console.log(`${done}/${n} ${label} (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
          });
          child.on("exit", (code) => (code ? reject(new Error(`worker ${k} failed`)) : resolve()));
        }),
    ),
  ).then(() => out);
}

/** Write src/library-data.ts. */
export function writeLibrary(library: Record<string, string[]>, likes: Record<string, string[]>): void {
  const lists = Object.entries(library)
    .map(([g, codes]) => `  ${g}: [\n${codes.map((c) => `    "${c}",`).join("\n")}\n  ],`)
    .join("\n");
  const liked = Object.entries(likes)
    .sort((a, b) => b[1].length - a[1].length)
    .map(([c, ids]) => `  ${c}: [${ids.map((id) => JSON.stringify(id)).join(", ")}],`)
    .join("\n");
  writeSafely(
    LIBRARY_FILE,
    `// Puzzle library, written by scripts/make-library.ts and scripts/add-likes.ts. Do not edit by hand.
// LIBRARY: puzzle codes per difficulty. LIKES: puzzle code -> ids of the browsers that liked it.
export const LIBRARY: Record<string, string[]> = {
${lists}
};
export const LIKES: Record<string, string[]> = {
${liked}
};
`,
  );
}
