// Generates the daily puzzles: one per difficulty per day, the same for everyone.
// They are made ahead of time and stored in src/daily-data.ts, so later changes to the
// generator never change a day's puzzles.
//
// Run: npm run dailies
//   FROM=2026-10-09  first day to (re)generate; earlier days are kept as they are
//   DAYS=400         days from START in total
//   START            first day of the list (only when starting a new list)
//   WORKERS=2        processes to run in parallel
// Hard, Expert and Extreme dailies are the best of a few candidates: the one whose hard
// steps are spread over the most separate places in the solve.
import { fork } from "node:child_process";
import { writeFileSync } from "node:fs";
import {
  DIFFICULTIES,
  Grid,
  SPREAD_TARGET,
  TECHNIQUES,
  TEMPLATES,
  encodePuzzle,
  generateRatedSync,
  logicalSolve,
  seededRandom,
  spreadOf,
  spreadScore,
} from "../src/engine";
import { DAILY, DAILY_START } from "../src/daily-data";

const START = process.env.START ?? DAILY_START;
const DAYS = Number(process.env.DAYS ?? 400);
const FROM = process.env.FROM ?? START;
const WORKERS = Number(process.env.WORKERS ?? 2);
const CANDIDATES = 3;
const TRIES = 3000;

const day = (i: number) => {
  const d = new Date(`${START}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + i);
  return d.toISOString().slice(0, 10);
};
// Stable seed per date and difficulty.
const seedOf = (s: string) => [...s].reduce((h, ch) => (Math.imul(h, 31) + ch.charCodeAt(0)) >>> 0, 2166136261);

function makeDay(date: string): string {
  return DIFFICULTIES.map((g) => {
    const rnd = seededRandom(seedOf(`${date}/${g}`));
    const allowed = TEMPLATES[g];
    const target = SPREAD_TARGET[g] ?? 0;
    if (!target) return encodePuzzle(generateRatedSync({ allowed }, rnd).puzzle);
    const tech = TECHNIQUES.filter((t) => allowed.includes(t.name));
    let best: { code: string; score: number } | null = null;
    for (let c = 0; c < CANDIDATES; c++) {
      const r = generateRatedSync({ allowed, spreadTries: TRIES }, rnd);
      const sp = spreadOf(logicalSolve(new Grid(r.puzzle), tech).steps);
      const score = spreadScore(sp);
      if (!best || score > best.score) best = { code: encodePuzzle(r.puzzle), score };
      if (sp.locks >= target) break;
    }
    return best!.code;
  }).join(" ");
}

if (process.env.DAILY_WORKER) {
  // Worker: make the days given by the parent and send them back one by one.
  const [part, parts] = process.env.DAILY_WORKER.split("/").map(Number);
  const first = Number(process.env.FIRST);
  for (let i = first + part; i < DAYS; i += parts) process.send!({ i, row: makeDay(day(i)) });
  process.exit(0);
} else {
  const rows: string[] = new Array(DAYS);
  const keepStart = Math.round((Date.parse(`${START}T12:00:00Z`) - Date.parse(`${DAILY_START}T12:00:00Z`)) / 86400000);
  let first = 0;
  while (first < DAYS && day(first) < FROM) {
    const old = DAILY[first + keepStart];
    if (!old) throw new Error(`No existing puzzles for ${day(first)} to keep; use an earlier FROM.`);
    rows[first] = old;
    first++;
  }
  console.log(`Keeping ${first} days, making ${DAYS - first} (${day(first)} to ${day(DAYS - 1)}) with ${WORKERS} workers.`);
  const t0 = Date.now();
  let done = 0;
  const workers = Array.from({ length: WORKERS }, (_, k) =>
    new Promise<void>((resolve, reject) => {
      const w = fork(process.argv[1], [], { env: { ...process.env, DAILY_WORKER: `${k}/${WORKERS}`, FIRST: String(first) } });
      w.on("message", (m: { i: number; row: string }) => {
        rows[m.i] = m.row;
        if (++done % 20 === 0) console.log(`${done} days (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
      });
      w.on("exit", (code) => (code ? reject(new Error(`worker ${k} failed`)) : resolve()));
    }),
  );
  Promise.all(workers).then(() => {
    writeFileSync(
      "src/daily-data.ts",
      `// Daily puzzles, generated by scripts/make-dailies.ts. Do not edit by hand.
// One line per day from DAILY_START: puzzle codes for ${DIFFICULTIES.join(", ")}.
export const DAILY_START = "${START}";
export const DAILY: string[] = [
${rows.map((r, i) => `  "${r}", // ${day(i)}`).join("\n")}
];
`,
    );
    console.log(`Wrote ${DAYS} days in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
  });
}
