// Generates the daily puzzles: one per difficulty per day, the same for everyone.
// They are made ahead of time and stored in src/daily-data.ts, so later changes to the
// generator never change a day's puzzles. Run: npm run dailies  (DAYS=400 by default)
import { writeFileSync } from "node:fs";
import { DIFFICULTIES, TEMPLATES, encodePuzzle, generateRatedSync, seededRandom } from "../src/engine";

const START = process.env.START ?? "2026-10-01";
const DAYS = Number(process.env.DAYS ?? 400);

const day = (i: number) => {
  const d = new Date(`${START}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + i);
  return d.toISOString().slice(0, 10);
};
// Stable seed per date and difficulty.
const seedOf = (s: string) => [...s].reduce((h, ch) => (Math.imul(h, 31) + ch.charCodeAt(0)) >>> 0, 2166136261);

const rows: string[] = [];
const t0 = Date.now();
for (let i = 0; i < DAYS; i++) {
  const date = day(i);
  const codes = DIFFICULTIES.map((g) => encodePuzzle(generateRatedSync({ allowed: TEMPLATES[g] }, seededRandom(seedOf(`${date}/${g}`))).puzzle));
  rows.push(`  "${codes.join(" ")}", // ${date}`);
  if (i % 25 === 0) console.log(`${date}  (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
}
writeFileSync(
  "src/daily-data.ts",
  `// Daily puzzles, generated by scripts/make-dailies.ts. Do not edit by hand.
// One line per day from DAILY_START: puzzle codes for ${DIFFICULTIES.join(", ")}.
export const DAILY_START = "${START}";
export const DAILY: string[] = [
${rows.join("\n")}
];
`,
);
console.log(`Wrote ${DAYS} days in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
