// Generates the daily puzzles: one per difficulty per day, the same for everyone.
// They are made ahead of time and stored in src/daily-data.ts, so later changes to the
// generator never change a day's puzzles.
//
// Run: npm run dailies
//   FROM=2026-10-09  first day to (re)generate; earlier days are kept as they are
//   DAYS=400         days from START in total
//   START            first day of the list (only when starting a new list)
//   WORKERS=2        processes to run in parallel
// Hard, Expert and Extreme dailies have all the moves REQUIREMENTS asks for (see
// goodPuzzle in scripts/common.ts).
import { writeFileSync } from "node:fs";
import { DIFFICULTIES, seededRandom } from "../src/engine";
import { DAILY, DAILY_START } from "../src/daily-data";
import { goodPuzzle, parallel } from "./common";

const START = process.env.START ?? DAILY_START;
const DAYS = Number(process.env.DAYS ?? 400);
const FROM = process.env.FROM ?? START;
const WORKERS = Number(process.env.WORKERS ?? 2);

const day = (i: number) => {
  const d = new Date(`${START}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + i);
  return d.toISOString().slice(0, 10);
};
// Stable seed per date and difficulty.
const seedOf = (s: string) => [...s].reduce((h, ch) => (Math.imul(h, 31) + ch.charCodeAt(0)) >>> 0, 2166136261);

// Days before FROM are kept from the current file.
const keepStart = Math.round((Date.parse(`${START}T12:00:00Z`) - Date.parse(`${DAILY_START}T12:00:00Z`)) / 86400000);
let first = 0;
const kept: string[] = [];
while (first < DAYS && day(first) < FROM) {
  const old = DAILY[first + keepStart];
  if (!old) throw new Error(`No existing puzzles for ${day(first)} to keep; use an earlier FROM.`);
  kept.push(old);
  first++;
}
if (!process.env.POOL_PART) console.log(`Keeping ${first} days, making ${DAYS - first} (${day(first)} to ${day(DAYS - 1)}) with ${WORKERS} workers.`);

const makeDay = (i: number) =>
  DIFFICULTIES.map((g) => {
    const p = goodPuzzle(g, seededRandom(seedOf(`${day(first + i)}/${g}`)));
    if (p.missing) console.warn(`${day(first + i)} ${g}: ${p.missing} move(s) short`);
    return p.code;
  }).join(" ");

parallel(DAYS - first, makeDay, WORKERS, "days").then((made) => {
  const rows = [...kept, ...made];
  writeFileSync(
    "src/daily-data.ts",
    `// Daily puzzles, generated by scripts/make-dailies.ts. Do not edit by hand.
// One line per day from DAILY_START: puzzle codes for ${DIFFICULTIES.join(", ")}.
export const DAILY_START = "${START}";
export const DAILY: string[] = [
${rows.map((r, i) => `  "${r}", // ${day(i)}`).join("\n")}
];
`,
  );
  console.log(`Wrote ${DAYS} days.`);
});
